# Generated by Django 4.0 on 2022-01-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('invoice_number', models.CharField(blank=True, max_length=10, null=True)),
                ('commercial', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=10, null=True)),
                ('roof', models.CharField(blank=True, max_length=10, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('slant', models.CharField(choices=[('Pente', 'Pente'), ('1.30', '1.30'), ('1.45', '1.45'), ('1.60', '1.60')], default='Pente', max_length=20)),
                ('source', models.CharField(choices=[('Source', 'Source'), ('R1', 'R1'), ('CA', 'Ca'), ('Assistance', 'Assistance')], default='Source', max_length=20)),
            ],
        ),
    ]
