# Generated by Django 4.0 on 2022-01-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_fiche_owner_alter_fiche_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
