# Generated by Django 4.0 on 2022-01-27 20:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_alter_fiche_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
