# Generated by Django 4.0 on 2022-01-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0005_alter_fiche_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
