# Generated by Django 4.0 on 2022-01-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_remove_fiche_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='customer',
            field=models.CharField(default='glou', max_length=200),
            preserve_default=False,
        ),
    ]
