# Generated by Django 4.0 on 2022-01-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0008_fiche_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='customer',
        ),
    ]
