# Generated by Django 4.0 on 2022-01-28 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0011_rename_customer_fiche_last_name_fiche_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='commercial',
        ),
    ]
