# Generated by Django 4.0 on 2022-01-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0012_remove_fiche_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='cap_access',
            field=models.CharField(choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], default='Accès', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='cap_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='cap_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='cap_mess',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='cap_type',
            field=models.CharField(choices=[('Mur', 'Mur'), ('Parpaing', 'Parpaing'), ('Brique', 'Brique'), ('Béton', 'Béton'), ('Meulière', 'Meulière')], default='Mur', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_access',
            field=models.CharField(choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], default='Accès', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_floor',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_job',
            field=models.CharField(choices=[('Traitement', 'Traitement'), ('Injection', 'Injection'), ('Pulvérisation', 'Pulvérisation'), ('Injection + Pulvérisation', 'Injection + Pulvérisation')], default='Traitement', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='charpente_mess',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fait_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fait_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fait_length_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fait_masonry',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='fait_roof',
            field=models.CharField(choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], default='Toiture', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='hydro_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='hydro_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='hydro_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='hydro_roof',
            field=models.CharField(choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], default='Toiture', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='hydro_type',
            field=models.CharField(choices=[('Type', 'Type'), ('Incolore', 'Incolore'), ('Coloré gris', 'Coloré gris'), ('Coloré brun', 'Coloré brun'), ('Coloré rouge sombre', 'Coloré rouge sombre')], default='Type', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_access',
            field=models.CharField(choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], default='Accès', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_floor',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_mess',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='isol_trash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_access',
            field=models.CharField(choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], default='Accès', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_floor',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_mess',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='soufflage_trash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_access',
            field=models.CharField(choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], default='Accès', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_floor',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_mess',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='thermo_trash',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='waterproof_length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='waterproof_length_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='waterproof_masonry',
            field=models.CharField(choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='waterproof_roof',
            field=models.CharField(choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], default='Toiture', max_length=50),
        ),
        migrations.AddField(
            model_name='fiche',
            name='waterproof_type',
            field=models.CharField(choices=[('Type', 'Type'), ('Cheminée', 'Cheminée'), ('Solin', 'Solin'), ('Capucine', 'Capucine'), ('Noue', 'Noue')], default='Type', max_length=50),
        ),
    ]
