# Generated by Django 4.0 on 2022-01-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0015_fiche_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='charpente_job',
            field=models.CharField(choices=[('Traitement', 'Traitement'), ('Injection', 'Injection'), ('Pulvérisation', 'Pulvérisation'), ('Inj + Pul', 'Inj + Pul')], default='Traitement', max_length=50),
        ),
    ]
