# Generated by Django 4.0 on 2022-01-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0016_alter_fiche_charpente_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_area',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
