# Generated by Django 4.0 on 2022-01-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0017_alter_fiche_soufflage_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='cap_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='cap_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fait_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fait_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fait_length_num',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='hydro_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='hydro_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='hydro_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='infos',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_trash',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_trash',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_area',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_trash',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='waterproof_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='waterproof_length_num',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
