# Generated by Django 4.0 on 2022-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0018_alter_fiche_cap_color_alter_fiche_cap_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='slant',
            field=models.CharField(choices=[('Pente', 'Pente'), ('1.30', '30°'), ('1.45', '45°'), ('1.60', '1.60')], default='Pente', max_length=20),
        ),
    ]
