# Generated by Django 4.0 on 2022-01-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0019_alter_fiche_slant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='slant',
            field=models.CharField(choices=[('Pente', 'Pente'), ('30°', '1.30'), ('45°', '1.45'), ('60°', '1.60')], default='Pente', max_length=20),
        ),
    ]
