# Generated by Django 4.0 on 2022-01-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0020_alter_fiche_slant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_floor',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], default='Oui/Non', max_length=50),
        ),
    ]
