# Generated by Django 4.0 on 2022-01-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0022_alter_fiche_soufflage_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='cap_access',
            field=models.CharField(blank=True, choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='cap_mess',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='cap_type',
            field=models.CharField(blank=True, choices=[('Mur', 'Mur'), ('Parpaing', 'Parpaing'), ('Brique', 'Brique'), ('Béton', 'Béton'), ('Meulière', 'Meulière')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_access',
            field=models.CharField(blank=True, choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_floor',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_job',
            field=models.CharField(blank=True, choices=[('Traitement', 'Traitement'), ('Injection', 'Injection'), ('Pulvérisation', 'Pulvérisation'), ('Inj + Pul', 'Inj + Pul')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='charpente_mess',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fait_masonry',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='fait_roof',
            field=models.CharField(blank=True, choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='hydro_roof',
            field=models.CharField(blank=True, choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='hydro_type',
            field=models.CharField(blank=True, choices=[('Type', 'Type'), ('Incolore', 'Incolore'), ('Coloré gris', 'Coloré gris'), ('Coloré brun', 'Coloré brun'), ('Coloré rouge sombre', 'Coloré rouge sombre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_access',
            field=models.CharField(blank=True, choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_floor',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='isol_mess',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='slant',
            field=models.CharField(choices=[('Pente', 'Pente'), ('30°', '1.30'), ('45°', '1.45'), ('60°', '1.60')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_access',
            field=models.CharField(blank=True, choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='soufflage_mess',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='source',
            field=models.CharField(choices=[('Source', 'Source'), ('R1', 'R1'), ('CA', 'Ca'), ('Assistance', 'Assistance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_access',
            field=models.CharField(blank=True, choices=[('Accès', 'Accès'), ('Intérieur', 'Intérieur'), ('Extérieur', 'Extérieur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_floor',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='thermo_mess',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='waterproof_masonry',
            field=models.CharField(blank=True, choices=[('Oui/Non', 'Oui/Non'), ('Oui', 'Oui'), ('Non', 'Non')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='waterproof_roof',
            field=models.CharField(blank=True, choices=[('Toiture', 'Toiture'), ('Tuile mécanique', 'Tuile mécanique'), ('Tuile béton', 'Tuile béton'), ('Tuile plate', 'Tuile plate'), ('Ardoise', 'Ardoise'), ('Fibro-ciment', 'Fibro-ciment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='waterproof_type',
            field=models.CharField(blank=True, choices=[('Type', 'Type'), ('Cheminée', 'Cheminée'), ('Solin', 'Solin'), ('Capucine', 'Capucine'), ('Noue', 'Noue')], max_length=50),
        ),
    ]
