# Generated by Django 4.0 on 2022-01-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0024_alter_fiche_cap_access_alter_fiche_cap_mess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='infos',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
