# Generated by Django 4.0 on 2022-01-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0025_alter_fiche_infos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='post_code',
            field=models.IntegerField(max_length=5),
        ),
    ]
