# Generated by Django 4.0 on 2022-01-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0027_alter_fiche_charpente_area_alter_fiche_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='charpente_area',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
