# Generated by Django 4.0 on 2022-01-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('direction', 'DIRECTION'), ('commercial', 'COMMERCIAL'), ('technicien', 'TECHNICIEN')], default=None, max_length=20, null=True),
        ),
    ]
