# Generated by Django 4.0 on 2022-01-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('rôle', 'rôle'), ('direction', 'direction'), ('commercial', 'commercial'), ('technicien', 'technicien')], default=None, max_length=20, null=True),
        ),
    ]
