# Generated by Django 4.0 on 2022-01-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Direction', 'Direction'), ('Administratif', 'Administratif'), ('Commercial', 'Commercial'), ('Technicien', 'Technicien')], default=None, max_length=20, null=True),
        ),
    ]
