# Generated by Django 4.0 on 2022-01-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Rôle', 'Rôle'), ('Direction', 'Direction'), ('Administratif', 'Administratif'), ('Commercial', 'Commercial'), ('Technicien', 'Technicien')], default='Rôle', max_length=20),
        ),
    ]
