# Generated by Django 4.0.1 on 2022-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Rôle', 'Rôle'), ('Direction', 'Direction'), ('Administratif', 'Administratif'), ('Commercial', 'Commercial'), ('Technicien', 'Technicien')], default='Rôle', max_length=20, null=True),
        ),
    ]
