# Generated by Django 4.0.1 on 2022-02-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiche',
            options={'ordering': ['-created']},
        ),
    ]
