# Generated by Django 4.0.1 on 2022-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('product_1', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity_1', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_1', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price_1', models.CharField(blank=True, max_length=200, null=True)),
                ('vat_1', models.CharField(blank=True, max_length=200, null=True)),
                ('total_vat_1', models.CharField(blank=True, max_length=200, null=True)),
                ('total_full_1', models.CharField(blank=True, max_length=200, null=True)),
                ('total_ht', models.CharField(blank=True, max_length=200, null=True)),
                ('total_vat', models.CharField(blank=True, max_length=200, null=True)),
                ('total_full', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
