# Generated by Django 4.0.1 on 2022-02-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_devi_product_2_devi_quantity_2_devi_total_full_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devi',
            name='product_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='quantity_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='total_full_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='total_vat_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='unit_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='unit_price_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devi',
            name='vat_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
