# Generated by Django 4.0.1 on 2022-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_devi_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devi',
            name='total_full',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_1',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_10',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_2',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_3',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_4',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_5',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_6',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_7',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_8',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_full_9',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_ht',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_1',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_10',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_2',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_3',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_4',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_5',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_6',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_7',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_8',
        ),
        migrations.RemoveField(
            model_name='devi',
            name='total_vat_9',
        ),
    ]
