export const CLIENTS_LIST_REQUEST = 'CLIENTS_LIST_REQUEST';
export const CLIENTS_LIST_SUCCESS = 'CLIENTS_LIST_SUCCESS';
export const CLIENTS_LIST_FAIL = 'CLIENTS_LIST_FAIL';

export const CLIENT_LIST_REQUEST = 'CLIENT_LIST_REQUEST';
export const CLIENT_LIST_SUCCESS = 'CLIENT_LIST_SUCCESS';
export const CLIENT_LIST_FAIL = 'CLIENT_LIST_FAIL';