export const DEVIS_LIST_REQUEST = 'DEVIS_LIST_REQUEST';
export const DEVIS_LIST_SUCCESS = 'DEVIS_LIST_SUCCESS';
export const DEVIS_LIST_FAIL = 'DEVIS_LIST_FAIL';

export const DEVI_LIST_REQUEST = 'DEVI_LIST_REQUEST';
export const DEVI_LIST_SUCCESS = 'DEVI_LIST_SUCCESS';
export const DEVI_LIST_FAIL = 'DEVI_LIST_FAIL';