export const FACTURES_LIST_REQUEST = 'FACTURES_LIST_REQUEST';
export const FACTURES_LIST_SUCCESS = 'FACTURES_LIST_SUCCESS';
export const FACTURES_LIST_FAIL = 'FACTURES_LIST_FAIL';

export const FACTURE_LIST_REQUEST = 'FACTURE_LIST_REQUEST';
export const FACTURE_LIST_SUCCESS = 'FACTURE_LIST_SUCCESS';
export const FACTURE_LIST_FAIL = 'FACTURE_LIST_FAIL';