export const FICHES_LIST_REQUEST = 'FICHES_LIST_REQUEST';
export const FICHES_LIST_SUCCESS = 'FICHES_LIST_SUCCESS';
export const FICHES_LIST_FAIL = 'FICHES_LIST_FAIL';

export const FICHE_LIST_REQUEST = 'FICHE_LIST_REQUEST';
export const FICHE_LIST_SUCCESS = 'FICHE_LIST_SUCCESS';
export const FICHE_LIST_FAIL = 'FICHE_LIST_FAIL';